server:
  port: 9001

eureka:
  client:
    service-url:
      defaultZone: http://172.28.1.11:5000/eureka/, http://172.28.1.12:5000/eureka/, http://172.28.1.13:5000/eureka/

feign:
  hystrix:
    enabled: true