# java -jar registry-center-1.0.0.jar
# 单节点配置
server:
  port: 5001
eureka:
  instance:
    hostname: localhost
    preferIpAddress: false
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/