spring:
    datasource:
        utesta:
            driverClassName: com.mysql.jdbc.Driver
            url: jdbc:mysql://localhost:3306/utestA?useUnicode=true&characterEncoding=utf-8
            username: root
            password: root
        utestb:
            driverClassName: com.mysql.jdbc.Driver
            url: jdbc:mysql://localhost:3306/utestB?useUnicode=true&characterEncoding=utf-8
            username: root
            password: root

mybatis:
    configLocation: classpath:config/system/mybatis/mybatis-config.xml
    # mapperLocations: classpath:config/system/mybatis/mapper/**/*.xml
    # typeAliasesPackage: com.utrons.**.model
